// ignore_for_file: unnecessary_string_escapes

import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "My Booking": "My Booking",
          "Wallet": "Wallet",
          "Rate us": "Rate us",
          "rafer": "Refer & Earn",
        },
        'hi_US': {
          "Settings": "समायोजन",
          "Account Settings": "अकाउंट सेटिंग",
          "Profile": "प्रोफ़ाइल",
          "My Booking": "मेरी बुकिंग",
          "Wallet": "बटुआ",
          "Favorite": "पसंदीदा",
          "Notification": "अधिसूचना",
          "Refer a Friend": "मित्र को आमंत्रित करें",
          "Dark Mode": "डार्क मोड",
          "Contact Us": "संपर्क करें",
          "Privacy Policy": "गोपनीयता नीति",
          "Terms & Condition": "नियम व शर्त",
          "FAQ": "सामान्य प्रश्न",
          "Langauge": "भाषा",
          "Help": "मदद",
          "Delete Account": "खाता हटा दो",
          "Are you sure ?\n You want to delete the account":
              "क्या आप सुनिश्चित हैं ?\n आप खाता हटाना चाहते हैं",
          "Logout": "लॉग आउट",
          "Delete": "मिटाना",
          "No": "नहीं",
          "Are you sure you want to log out?":
              "क्या आप लॉग आउट करना चाहते हैं?",
          "Cancel": "रद्द करना",
          "Yes Logout": "हाँ लॉग आउट करें",
          "Search": "खोज",
          "Invite": "आमंत्रित करना",
          "About Event": "घटना के बारे में",
          "Gallery": "गेलरी",
          "Organizer": "व्यवस्था करनेवाला",
          "View E-Ticket": "ई-टिकट देखें",
          "Buy More Ticket": "अधिक टिकट खरीदें",
          "Looks like you haven't booked yet":
              "लगता है आपने अभी तक बुक नहीं किया है",
          "Members": "सदस्यों",
          "Explore": "खोजना",
          "Booking": "बुकिंग",
          "Tickets": "टिकट",
          "Upcoming": "आगामी",
          "Completed": "पूरा हुआ",
          "Cancelled": "रद्द",
          "Download Ticket": "टिकट डाउनलोड करें",
          "E-Ticket": "ई-टिकट",
          "Event": "आयोजन",
          "Date and Hour": "दिनांक और घंटा",
          "Event Location": "घटना स्थान",
          "Event organizer": "कार्यक्रम के आयोजक",
          "Full Name": "पूरा नाम",
          "Phone": "फ़ोन",
          "Email": "ईमेल",
          "Seats": "सीटों",
          "Tax": "कर",
          "Total": "संपूर्ण",
          "Transaction ID": "लेन-देन आईडी",
          "Payment Methods": "भुगतान की विधि",
          "Status": "दर्जा",
          "Copy": "प्रतिलिपि",
          "BUY TICKET": "टिकट खरीदें",
          "Trending Events": "ट्रेंडिंग इवेंट्स",
          "See All": "सभी देखें",
          "Upcoming Events": "आने वाले कार्यक्रम",
          "Invite your friends": "अपने दोस्तों को आमंत्रित करें",
          "Get \$20 for ticket": "टिकट के लिए \$20 प्राप्त करें",
          "INVITE": "आमंत्रित करना",
          "Nearby You": "आप के पास",
          "Event This Month": "इस महीने की घटना",
          "Sponser": "प्रायोजक",
          "Join": "जोड़ना",
          "Current Location": "वर्तमान स्थान",
          "Search...": "खोज...",
          "Angelina Zolly": "एंजेलीना जॉली",
          "2k Followers": "2k अनुयायी",
          "Bookmark": "बुकमार्क",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Name": "नाम",
          "Number": "संख्या",
          "password": "कूटशब्द",
          "SAVE": "बचाना",
          "Event Details": "घटना की जानकारी",
          "Directions": "दिशा-निर्देश",
          "CONTINUE": "जारी रखें",
          "Ticket": "टिकट",
          "Ticket Type": "टिकिट का प्रकार",
          "Seat": "सीट",
          "Coupons": "कूपन",
          "Coupon applied !": "कूपन लागू किया गया !",
          "Apply Coupon": "कूपन लागू करें",
          "Applied Voucher Code": "एप्लाइड वाउचर कोड",
          "Pay from wallet": "वॉलेट से भुगतान करें",
          "GoEvent Balance": "गोइवेंट बैलेंस",
          "Available for Payment ": "भुगतान हेतु उपलब्ध है ",
          "Sub Total:": "उप योग:",
          "Wallet:": "बटुआ:",
          "Coupon Code:": "कूपन कोड:",
          "Tax:": "कर:",
          "Total:": "संपूर्ण:",
          "I Confirm that I am healty": "मैं पुष्टि करता हूं कि मैं स्वस्थ हूं",
          "Select Payment Method": "भुगतान का तरीका चुनें",
          "PAY NOW | ": "अभी भुगतान करें |",
          "Add Your payment information": "अपनी भुगतान जानकारी जोड़ें",
          "What number is written on card?": "कार्ड पर कौन सा नंबर लिखा है?",
          "Number behind the card": "कार्ड के पीछे नंबर",
          "CVV": "सीवीवी",
          "Expiry Date": "समाप्ति तिथि",
          "MM/YY": "महीना साल",
          "Event Venue": "आयोजन स्थल",
          "Event List Not Found!": "इवेंट सूची नहीं मिली!",
          "Helps & FAQs": "सहायता और अक्सर पूछे जाने वाले प्रश्न",
          "Refer a friend": "मित्र को आमंत्रित करें",
          "Add": "जोड़ें",
          "Add Wallet": "बटुआ जोड़ें",
          "Your current Balance ": "आपका वर्तमान शेष",
          "Add Amount": "राशि जोड़ें",
          "Amount": "मात्रा",
          "History": "इतिहास",
          "Mr. Urban App": "मिस्टर अर्बन ऐप",
          "Congratulation !": "बधाई हो!",
          "DATE": "दिनांक",
          "TIME": "समय",
          "Location": "स्थान",
          "Please don`t press back until the transaction is complete":
              "लेन-देन पूरा होने तक कृपया वापस न दबाएं",
          "No New Notifications": "कोई नए संदेश नहीं",
          "No Event Shortlisted, Yet !":
              "कोई इवेंट शॉर्टलिस्ट नहीं किया गया, फिर भी!",
          "Available Coupon": "उपलब्ध कूपन",
          "No Coupon": "कोई कूपन नहीं",
          "Apply": "आवेदन करना",
          "Resset Password": "पासवर्ड रीसेट",
          "Please enter your email address to": "कृपया अपना ईमेल पता दर्ज करें",
          "request a password reset": "पासवर्ड रीसेट करने का अनुरोध करें",
          "New Password": "नया पासवर्ड",
          "confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "SEND": "भेजना",
          "GoEvent": "गोईवेंट",
          "Sign in": "साइन इन करें",
          "Mobile number": "मोबाइल नंबर",
          "Remember Me": "Remember Me",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "SIGN IN": "साइन इन करें",
          "Don't have an account?": "खाता नहीं है?",
          "Sign up": "साइन अप करें",
          "Enter Number": "नंबर डालें",
          "Your password": "आपका पासवर्ड",
          "Referral code": "रेफरल कोड",
          "By continuing, ": "जारी रखते हुए,",
          "You agree to GoEvent's \n": "आप गोइवेंट के \n से सहमत हैं",
          "Terms of Use ": "उपयोग की शर्तें",
          "Terms & Conditions": "नियम एवं शर्तें",
          "Privacy Policy.": "गोपनीयता नीति।",
          "SIGN UP": "साइन अप करें",
          "Already have an account? ": "पहले से ही एक खाता है?",
          "Verification": "सत्यापन",
          "We've send you the verification": "हमने आपको सत्यापन भेज दिया है",
          "Re-send OTP": "ओटीपी पुनः भेजें",
          "Comment": "टिप्पणी",
          "Enter comment": "टिप्पणी दर्ज करें",
          "Submit": "प्रस्तुत करना",
          "Cancel Booking": "बुकिंग रद्द करें",
          "Please select the reason for cancellation:":
              "कृपया रद्द करने का कारण चुनें:",
          "Enter reason": "कारण दर्ज करें",
          "Confirm": "पुष्टि करें",
        },
        'ZA_IN': {
          "Settings": "Marekebisho",
          "Account Settings": "mipangilio ya akaunti",
          "Profile": "Wasifu",
          "My Booking": "uhifadhi wangu",
          "Wallet": "mfuko wa fedha",
          "Favorite": "Kipendwa",
          "Notification": "taarifa",
          "Refer a Friend": "mwalike rafiki",
          "Dark Mode": "hali ya giza",
          "Contact Us": "Wasiliana",
          "Privacy Policy": "Sera ya Faragha",
          "Terms & Condition": "sheria na Masharti",
          "FAQ": "swali la jumla",
          "Langauge": "Lugha",
          "Help": "msaada",
          "Delete Account": "kufuta akaunti",
          "Are you sure ?\n You want to delete the account":
              "Je, una uhakika?\n Unataka kufuta akaunti",
          "Logout": "ingia nje",
          "Delete": "kufuta",
          "No": "Hapana",
          "Are you sure you want to log out?":
              "Je, una uhakika unataka kutoka?",
          "Cancel": "Ghairi",
          "Yes Logout": "ndio ingia nje",
          "Search": "Tafuta",
          "Invite": "kukaribisha",
          "About Event": "kuhusu tukio hilo",
          "Gallery": "Matunzio",
          "Organizer": "Mratibu",
          "View E-Ticket": "angalia tikiti ya elektroniki",
          "Buy More Ticket": "nunua tikiti zaidi",
          "Looks like you haven't booked yet":
              "Inaonekana bado hujaweka nafasi",
          "Members": "wanachama",
          "Explore": "kutafuta",
          "Booking": "kuweka nafasi",
          "Tickets": "Tikiti",
          "Upcoming": "ujao",
          "Completed": "Imekamilika",
          "Cancelled": "Imeghairiwa",
          "Download Ticket": "tikiti ya kupakua",
          "E-Ticket": "tikiti ya kielektroniki",
          "Event": "Shirika",
          "Date and Hour": "tarehe na saa",
          "Event Location": "eneo la tukio",
          "Event organizer": "mratibu wa tukio",
          "Full Name": "Jina kamili",
          "Phone": "simu",
          "Email": "Barua pepe",
          "Seats": "viti",
          "Tax": "fanya",
          "Total": "kamili",
          "Transaction ID": "kitambulisho cha muamala",
          "Payment Methods": "njia ya malipo",
          "Status": "hali",
          "Copy": "nakala",
          "BUY TICKET": "kununua tiketi",
          "Trending Events": "matukio yanayovuma",
          "See All": "ona yote",
          "Upcoming Events": "matukio yajayo",
          "Invite your friends": "waalike marafiki zako",
          "Get \$20 for ticket": "PATA \$20 KWA TIKETI",
          "INVITE": "kukaribisha",
          "Nearby You": "karibu na wewe",
          "Event This Month": "tukio la mwezi",
          "Sponser": "mfadhili",
          "Join": "kujiunga",
          "Current Location": "Eneo la Sasa",
          "Search...": "Tafuta...",
          "Angelina Zolly": "Angelina Jolie",
          "2k Followers": "wafuasi 2k",
          "Bookmark": "alamisho",
          "Edit Profile": "hariri Wasifu",
          "Name": "jina",
          "Number": "Nambari",
          "password": "nenosiri",
          "SAVE": "kuokoa",
          "Event Details": "habari ya tukio",
          "Directions": "miongozo",
          "CONTINUE": "endelea",
          "Ticket": "Tikiti",
          "Ticket Type": "Aina ya Tiketi",
          "Seat": "kiti",
          "Coupons": "Kuponi",
          "Coupon applied !": "Kuponi imetumika!",
          "Apply Coupon": "Tumia Kuponi",
          "Applied Voucher Code": "Msimbo wa Vocha Uliotumika",
          "Pay from wallet": "lipa kwa mkoba",
          "GoEvent Balance": "usawa wa goevent",
          "Available for Payment ": "inapatikana kwa malipo",
          "Sub Total:": "Tumia:",
          "Wallet:": "mfuko wa fedha:",
          "Coupon Code:": "Msimbo wa Kuponi:",
          "Tax:": "fanya:",
          "Total:": "kamili:",
          "I Confirm that I am healty":
              "Ninathibitisha kuwa mimi ni mzima wa afya",
          "Select Payment Method": "Chagua Njia ya Kulipa",
          "PAY NOW | ": "Lipa Sasa |",
          "Add Your payment information": "ongeza maelezo yako ya malipo",
          "What number is written on card?":
              "Nambari gani imeandikwa kwenye kadi?",
          "Number behind the card": "nambari iliyo nyuma ya kadi",
          "CVV": "cvv",
          "Expiry Date": "tarehe ya mwisho",
          "MM/YY": "mwaka wa mwezi",
          "Event Venue": "ukumbi",
          "Event List Not Found!": "Uorodheshaji wa matukio haujapatikana!",
          "Helps & FAQs": "Msaada na Maswali Yanayoulizwa Mara kwa Mara",
          "Refer a friend": "mwalike rafiki",
          "Add": "ongeza",
          "Add Wallet": "ongeza pochi",
          "Your current Balance ": "salio lako la sasa",
          "Add Amount": "ongeza kiasi",
          "Amount": "kiasi",
          "History": "historia",
          "Mr. Urban App": "programu ya mr mjini",
          "Congratulation !": "Hongera!",
          "DATE": "tarehe",
          "TIME": "wakati",
          "Location": "Mahali",
          "Please don`t press back until the transaction is complete":
              "Tafadhali usirudishe hadi shughuli ikamilike",
          "No New Notifications": "Hakuna arifa mpya",
          "No Event Shortlisted, Yet !":
              "Bado hakuna matukio yaliyoorodheshwa!",
          "Available Coupon": "Kuponi Zinapatikana",
          "No Coupon": "hakuna kuponi",
          "Apply": "Kuomba",
          "Resset Password": "kuweka upya nenosiri",
          "Please enter your email address to":
              "Tafadhali ingiza barua pepe yako",
          "request a password reset": "omba kuweka upya nenosiri",
          "New Password": "Nenosiri Mpya",
          "confirm Password": "Thibitisha Nenosiri",
          "SEND": "tuma",
          "GoEvent": "goevent",
          "Sign in": "Weka sahihi",
          "Mobile number": "namba ya simu ya mkononi",
          "Remember Me": "Nikumbuke",
          "Forgot Password?": "Umesahau nywila?",
          "SIGN IN": "Weka sahihi",
          "Don't have an account?": "Je, huna akaunti?",
          "Sign up": "Jisajili",
          "Enter Number": "ingiza nambari",
          "Your password": "nenosiri lako",
          "Referral code": "Msimbo wa Rufaa",
          "By continuing, ": "kuendelea,",
          "You agree to GoEvent's \n": "Unakubaliana na GoEvent\n",
          "Terms of Use ": "masharti ya matumizi",
          "Terms & Conditions": "sheria na Masharti",
          "Privacy Policy.": "Sera ya Faragha.",
          "SIGN UP": "Jisajili",
          "Already have an account? ": "Je, tayari una akaunti?",
          "Verification": "uthibitishaji",
          "We've send you the verification": "Tumekutumia uthibitishaji",
          "Re-send OTP": "Tuma tena OTP",
          "Comment": "Maoni",
          "Enter comment": "ingiza maoni",
          "Submit": "kuwasilisha au kuonyesha",
          "Cancel Booking": "ghairi uhifadhi",
          "Please select the reason for cancellation:":
              "Tafadhali chagua sababu ya kughairi:",
          "Enter reason": "ingiza sababu",
          "Confirm": "thibitisha",
        },
        'ar_IN': {
          "Settings": "تعديل",
          "Account Settings": "إعدادت الحساب",
          "Profile": "حساب تعريفي",
          "My Booking": "الحجز",
          "Wallet": "كيس نقود",
          "Favorite": "مفضل",
          "Notification": "إشعار",
          "Refer a Friend": "دعوة صديق",
          "Dark Mode": "الوضع المظلم",
          "Contact Us": "اتصال",
          "Privacy Policy": "سياسة الخصوصية",
          "Terms & Condition": "الأحكام والشروط",
          "FAQ": "سؤال عام",
          "Langauge": "لغة",
          "Help": "مساعدة",
          "Delete Account": "حذف الحساب",
          "Are you sure ?\n You want to delete the account":
              "هل أنت متأكد؟ \ n تريد حذف الحساب",
          "Logout": "تسجيل خروج",
          "Delete": "حذف",
          "No": "رقم",
          "Are you sure you want to log out?":
              "هل أنت متأكد أنك تريد تسجيل الخروج؟",
          "Cancel": "يلغي",
          "Yes Logout": "نعم تسجيل الخروج",
          "Search": "يبحث",
          "Invite": "يدعو",
          "About Event": "عن الحدث",
          "Gallery": "صالة عرض",
          "Organizer": "منظم",
          "View E-Ticket": "عرض التذكرة الإلكترونية",
          "Buy More Ticket": "شراء المزيد من التذاكر",
          "Looks like you haven't booked yet": "يبدو أنك لم تحجز بعد",
          "Members": "أفراد",
          "Explore": "للبحث",
          "Booking": "الحجز",
          "Tickets": "تذكرة",
          "Upcoming": "القادم",
          "Completed": "انتهى",
          "Cancelled": "ألغيت",
          "Download Ticket": "تنزيل التذكرة",
          "E-Ticket": "تذكرة إلكترونية",
          "Event": "منظمة",
          "Date and Hour": "التاريخ والساعة",
          "Event Location": "موقع الحدث",
          "Event organizer": "منظم الحدث",
          "Full Name": "الاسم بالكامل",
          "Phone": "هاتف",
          "Email": "بريد إلكتروني",
          "Seats": "المقاعد",
          "Tax": "فعل",
          "Total": "اكتمال",
          "Transaction ID": "رقم المعاملة",
          "Payment Methods": "طريقة الدفع او السداد",
          "Status": "الحالة",
          "Copy": "ينسخ",
          "BUY TICKET": "اشتري تذكرة",
          "Trending Events": "تتجه الأحداث",
          "See All": "اظهار الكل",
          "Upcoming Events": "الأحداث القادمة",
          "Invite your friends": "اعزم أصحابك",
          "Get \$20 for ticket": "احصل على 20 دولارًا للتذاكر",
          "INVITE": "يدعو",
          "Nearby You": "بالقرب منك",
          "Event This Month": "حدث الشهر",
          "Sponser": "كفيل",
          "Join": "انضم",
          "Current Location": "الموقع الحالي",
          "Search...": "يبحث...",
          "Angelina Zolly": "أنجلينا جولي",
          "2k Followers": "2 ألف متابع",
          "Bookmark": "المرجعية",
          "Edit Profile": "تعديل الملف الشخصي",
          "Name": "اسم",
          "Number": "رقم",
          "password": "كلمه السر",
          "SAVE": "حفظ",
          "Event Details": "دعوة معلومات",
          "Directions": "القواعد الارشادية",
          "CONTINUE": "استمر",
          "Ticket": "تذكرة",
          "Ticket Type": "نوع التذكرة",
          "Seat": "مقعد",
          "Coupons": "كوبونات",
          "Coupon applied !": "تم تطبيق القسيمة!",
          "Apply Coupon": "تطبيق القسيمة",
          "Applied Voucher Code": "رمز القسيمة المطبقة",
          "Pay from wallet": "ادفع بالمحفظة",
          "GoEvent Balance": "التوازن goevent",
          "Available for Payment ": "متاح للدفع",
          "Sub Total:": "يستخدم:",
          "Wallet:": "كيس نقود:",
          "Coupon Code:": "رمز الكوبون:",
          "Tax:": "فعل:",
          "Total:": "اكتمال:",
          "I Confirm that I am healty": "أؤكد أنني بصحة جيدة",
          "Select Payment Method": "اختار طريقة الدفع",
          "PAY NOW | ": "ادفع الآن |",
          "Add Your payment information": "أضف معلومات الدفع الخاصة بك",
          "What number is written on card?": "ما هو الرقم المكتوب على البطاقة؟",
          "Number behind the card": "رقم على ظهر البطاقة",
          "CVV": "السيرة الذاتية",
          "Expiry Date": "تاريخ الانتهاء",
          "MM/YY": "شهر سنة",
          "Event Venue": "مكان",
          "Event List Not Found!": "قائمة الأحداث غير موجودة!",
          "Helps & FAQs": "المساعدة والأسئلة الشائعة",
          "Refer a friend": "دعوة صديق",
          "Add": "يضيف",
          "Add Wallet": "أضف المحفظة",
          "Your current Balance ": "رصيدك الحالي",
          "Add Amount": "أضف المبلغ",
          "Amount": "مقدار",
          "History": "التاريخ",
          "Mr. Urban App": "تطبيق السيد الحضري",
          "Congratulation !": "تهانينا!",
          "DATE": "تاريخ",
          "TIME": "الوقت",
          "Location": "موقع",
          "Please don`t press back until the transaction is complete":
              "من فضلك لا تضغط مرة أخرى حتى تكتمل المعاملة",
          "No New Notifications": "لا يوجد إشعارات جديدة",
          "No Event Shortlisted, Yet !":
              "لا توجد أحداث في القائمة المختصرة حتى الآن!",
          "Available Coupon": "القسائم المتاحة",
          "No Coupon": "لا كوبونات",
          "Apply": "أن يطلب",
          "Resset Password": "إعادة تعيين كلمة المرور",
          "Please enter your email address to":
              "الرجاء إدخال عنوان البريد الإلكتروني الخاص بك",
          "request a password reset": "اعادة تعيين كلمة المرور طلب",
          "New Password": "كلمة سر جديدة",
          "confirm Password": "تأكيد كلمة المرور",
          "SEND": "إرسال",
          "GoEvent": "غيفينت",
          "Sign in": "تسجيل الدخول",
          "Mobile number": "رقم الهاتف المحمول",
          "Remember Me": "تذكرنى",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "SIGN IN": "تسجيل الدخول",
          "Don't have an account?": "ليس لديك حساب؟",
          "Sign up": "اشتراك",
          "Enter Number": "أدخل رقم",
          "Your password": "كلمة مرورك",
          "Referral code": "كود الإحالة",
          "By continuing, ": "مستمر ،",
          "You agree to GoEvent's \n": "أنت توافق على GoEvent \ n",
          "Terms of Use ": "تعليمات الاستخدام",
          "Terms & Conditions": "الأحكام والشروط",
          "Privacy Policy.": "سياسة الخصوصية.",
          "SIGN UP": "اشتراك",
          "Already have an account? ": "هل لديك حساب؟",
          "Verification": "تَحَقّق",
          "We've send you the verification": "لقد أرسلنا لك التحقق",
          "Re-send OTP": "إعادة إرسال OTP",
          "Comment": "تعليق",
          "Enter comment": "أدخل التعليق",
          "Submit": "للتقديم أو العرض",
          "Cancel Booking": "إلغاء الحجز",
          "Please select the reason for cancellation:":
              "الرجاء تحديد سبب الإلغاء:",
          "Enter reason": "أدخل السبب",
          "Confirm": "تؤكد",
        },
        'nl_IN': {
          "Settings": "Aanpassing",
          "Account Settings": "account instellingen",
          "Profile": "Profiel",
          "My Booking": "mijn boeking",
          "Wallet": "handtas",
          "Favorite": "Favoriete",
          "Notification": "kennisgeving",
          "Refer a Friend": "nodig een vriend uit",
          "Dark Mode": "donkere modus",
          "Contact Us": "Contact",
          "Privacy Policy": "Privacybeleid",
          "Terms & Condition": "voorwaarden",
          "FAQ": "algemene vraag",
          "Langauge": "Taal",
          "Help": "helpen",
          "Delete Account": "account verwijderen",
          "Are you sure ?\n You want to delete the account":
              "Weet je het zeker?\n Je wilt het account verwijderen",
          "Logout": "uitloggen",
          "Delete": "verwijderen",
          "No": "Nee",
          "Are you sure you want to log out?":
              "Weet je zeker dat je wilt uitloggen?",
          "Cancel": "Annuleren",
          "Yes Logout": "ja uitloggen",
          "Search": "Zoeken",
          "Invite": "uitnodiging",
          "About Event": "over het evenement",
          "Gallery": "Galerij",
          "Organizer": "Organisator",
          "View E-Ticket": "e-ticket bekijken",
          "Buy More Ticket": "meer kaartjes kopen",
          "Looks like you haven't booked yet":
              "Het lijkt erop dat je nog niet hebt geboekt",
          "Members": "leden",
          "Explore": "zoeken",
          "Booking": "boeken",
          "Tickets": "Ticket",
          "Upcoming": "de komende",
          "Completed": "Het is klaar",
          "Cancelled": "Geannuleerd",
          "Download Ticket": "kaartje downloaden",
          "E-Ticket": "e-ticket",
          "Event": "Organisatie",
          "Date and Hour": "datum en uur",
          "Event Location": "evenement locatie",
          "Event organizer": "evenement organisator",
          "Full Name": "Voor-en achternaam",
          "Phone": "telefoon",
          "Email": "E-mailen",
          "Seats": "de stoelen",
          "Tax": "doen",
          "Total": "compleet",
          "Transaction ID": "Transactie ID",
          "Payment Methods": "betalingsmiddel",
          "Status": "toestand",
          "Copy": "kopiëren",
          "BUY TICKET": "koop ticket",
          "Trending Events": "trending evenementen",
          "See All": "alles zien",
          "Upcoming Events": "aankomende evenementen",
          "Invite your friends": "nodig je vrienden uit",
          "Get \$20 for ticket": "KRIJG \$20 VOOR TICKETS",
          "INVITE": "uitnodiging",
          "Nearby You": "dichtbij jou",
          "Event This Month": "evenement van de maand",
          "Sponser": "sponsor",
          "Join": "meedoen",
          "Current Location": "Huidige locatie",
          "Search...": "Zoeken...",
          "Angelina Zolly": "Angelina Jolie",
          "2k Followers": "2k volgers",
          "Bookmark": "bladwijzer",
          "Edit Profile": "bewerk profiel",
          "Name": "naam",
          "Number": "Nummer",
          "password": "wachtwoord",
          "SAVE": "sparen",
          "Event Details": "evenement informatie",
          "Directions": "richtlijnen",
          "CONTINUE": "doorgaan",
          "Ticket": "Ticket",
          "Ticket Type": "Tickettype",
          "Seat": "stoel",
          "Coupons": "Waardebonnen",
          "Coupon applied !": "Coupon is toegepast!",
          "Apply Coupon": "Bon gebruiken",
          "Applied Voucher Code": "Toegepaste vouchercode",
          "Pay from wallet": "betalen met portemonnee",
          "GoEvent Balance": "goede balans",
          "Available for Payment ": "beschikbaar voor betaling",
          "Sub Total:": "Gebruiken:",
          "Wallet:": "handtas:",
          "Coupon Code:": "Coupon code:",
          "Tax:": "doen:",
          "Total:": "compleet:",
          "I Confirm that I am healty": "Ik bevestig dat ik gezond ben",
          "Select Payment Method": "Selecteer betaalmethode",
          "PAY NOW | ": "Betaal nu |",
          "Add Your payment information": "voeg uw betalingsgegevens toe",
          "What number is written on card?": "Welk nummer staat op de kaart?",
          "Number behind the card": "nummer op de achterkant van de kaart",
          "CVV": "cvv",
          "Expiry Date": "einddatum",
          "MM/YY": "maand jaar",
          "Event Venue": "de locatie",
          "Event List Not Found!": "Evenementenlijst niet gevonden!",
          "Helps & FAQs": "Hulp en veelgestelde vragen",
          "Refer a friend": "nodig een vriend uit",
          "Add": "toevoegen",
          "Add Wallet": "portemonnee toevoegen",
          "Your current Balance ": "uw huidige saldo",
          "Add Amount": "bedrag toevoegen",
          "Amount": "hoeveelheid",
          "History": "geschiedenis",
          "Mr. Urban App": "mijnheer stedelijke app",
          "Congratulation !": "Gefeliciteerd!",
          "DATE": "datum",
          "TIME": "tijd",
          "Location": "Plaats",
          "Please don`t press back until the transaction is complete":
              "Druk niet terug totdat de transactie is voltooid",
          "No New Notifications": "geen nieuwe notificaties",
          "No Event Shortlisted, Yet !":
              "Er zijn nog geen evenementen op de shortlist!",
          "Available Coupon": "Waardebonnen beschikbaar",
          "No Coupon": "geen coupons",
          "Apply": "aanvragen",
          "Resset Password": "wachtwoord reset",
          "Please enter your email address to":
              "Vul alstublieft uw e-mail adres in",
          "request a password reset": "Wachtwoord reset aanvragen",
          "New Password": "nieuw paswoord",
          "confirm Password": "bevestig wachtwoord",
          "SEND": "versturen",
          "GoEvent": "evenement",
          "Sign in": "Log in",
          "Mobile number": "mobiel nummer",
          "Remember Me": "onthoud mij",
          "Forgot Password?": "Wachtwoord vergeten?",
          "SIGN IN": "Log in",
          "Don't have an account?": "Heb je geen account?",
          "Sign up": "Inschrijven",
          "Enter Number": "Voer nummer in",
          "Your password": "uw wachtwoord",
          "Referral code": "Verwijzingscode",
          "By continuing, ": "doorgaan,",
          "You agree to GoEvent's \n": "U gaat akkoord met GoEvent\n",
          "Terms of Use ": "gebruiksvoorwaarden",
          "Terms & Conditions": "voorwaarden",
          "Privacy Policy.": "Privacybeleid.",
          "SIGN UP": "Inschrijven",
          "Already have an account? ": "Heb je al een account?",
          "Verification": "verificatie",
          "We've send you the verification":
              "We hebben u een verificatie gestuurd",
          "Re-send OTP": "OTP opnieuw verzenden",
          "Comment": "Opmerking",
          "Enter comment": "voer commentaar in",
          "Submit": "presenteren of laten zien",
          "Cancel Booking": "boeking annuleren",
          "Please select the reason for cancellation:":
              "Selecteer een reden voor annulering:",
          "Enter reason": "voer de reden in",
          "Confirm": "bevestigen",
        },
        'de_IN': {
          "Settings": "Ajustement",
          "Account Settings": "paramètres du compte",
          "Profile": "Profil",
          "My Booking": "ma réservation",
          "Wallet": "sac",
          "Favorite": "Préféré",
          "Notification": "notification",
          "Refer a Friend": "inviter un ami",
          "Dark Mode": "mode sombre",
          "Contact Us": "Contacter",
          "Privacy Policy": "Politique de confidentialité",
          "Terms & Condition": "termes et conditions",
          "FAQ": "question générale",
          "Langauge": "Langue",
          "Help": "aider",
          "Delete Account": "Supprimer le compte",
          "Are you sure ?\n You want to delete the account":
              "Êtes-vous sûr ?\n Vous souhaitez supprimer le compte",
          "Logout": "Se déconnecter",
          "Delete": "effacer",
          "No": "Non",
          "Are you sure you want to log out?":
              "Êtes-vous sûr de vouloir vous déconnecter?",
          "Cancel": "Annuler",
          "Yes Logout": "oui se déconnecter",
          "Search": "Rechercher",
          "Invite": "inviter",
          "About Event": "à propos de l'événement",
          "Gallery": "Galerie",
          "Organizer": "Organisateur",
          "View E-Ticket": "voir le billet électronique",
          "Buy More Ticket": "acheter plus de billets",
          "Looks like you haven't booked yet":
              "Il semble que vous n'ayez pas encore réservé",
          "Members": "membres",
          "Explore": "chercher",
          "Booking": "réservation",
          "Tickets": "Billet",
          "Upcoming": "le prochain",
          "Completed": "C'est fini",
          "Cancelled": "Annulé",
          "Download Ticket": "télécharger le billet",
          "E-Ticket": "billet électronique",
          "Event": "Organisme",
          "Date and Hour": "date et heure",
          "Event Location": "lieu de l'événement",
          "Event organizer": "organisateur de l'événement",
          "Full Name": "Nom et prénom",
          "Phone": "téléphone fixe",
          "Email": "E-mail",
          "Seats": "les sièges",
          "Tax": "faire",
          "Total": "Achevée",
          "Transaction ID": "identifiant de transaction",
          "Payment Methods": "mode de paiement",
          "Status": "statut",
          "Copy": "copie",
          "BUY TICKET": "Acheter un billet",
          "Trending Events": "événements tendance",
          "See All": "voir tout",
          "Upcoming Events": "évènements à venir",
          "Invite your friends": "invite tes amis",
          "Get \$20 for ticket": "OBTENEZ 20 \$ POUR LES BILLETS",
          "INVITE": "inviter",
          "Nearby You": "près de toi",
          "Event This Month": "événement du mois",
          "Sponser": "parrainer",
          "Join": "rejoindre",
          "Current Location": "Localisation actuelle",
          "Search...": "Rechercher...",
          "Angelina Zolly": "Angelina Jolie",
          "2k Followers": "2 000 abonnés",
          "Bookmark": "signet",
          "Edit Profile": "Editer le profil",
          "Name": "Nom",
          "Number": "Nombre",
          "password": "le mot de passe",
          "SAVE": "sauvegarder",
          "Event Details": "informations sur l'événement",
          "Directions": "des lignes directrices",
          "CONTINUE": "Continuez",
          "Ticket": "Billet",
          "Ticket Type": "Type de billet",
          "Seat": "siège",
          "Coupons": "Coupons",
          "Coupon applied !": "Le coupon a été appliqué !",
          "Apply Coupon": "Appliquer Coupon",
          "Applied Voucher Code": "Code de bon appliqué",
          "Pay from wallet": "payer avec portefeuille",
          "GoEvent Balance": "bilan de l'événement",
          "Available for Payment ": "disponible pour paiement",
          "Sub Total:": "Utiliser:",
          "Wallet:": "sac:",
          "Coupon Code:": "Code promo :",
          "Tax:": "faire:",
          "Total:": "Achevée:",
          "I Confirm that I am healty":
              "Je confirme que je suis en bonne santé",
          "Select Payment Method": "Sélectionnez le mode de paiement",
          "PAY NOW | ": "Payez maintenant |",
          "Add Your payment information":
              "ajouter vos informations de paiement",
          "What number is written on card?":
              "Quel numéro est inscrit sur la carte ?",
          "Number behind the card": "numéro au dos de la carte",
          "CVV": "cvv",
          "Expiry Date": "date de fin",
          "MM/YY": "mois année",
          "Event Venue": "le lieu",
          "Event List Not Found!": "Liste d'événements introuvable !",
          "Helps & FAQs": "Aide et FAQ",
          "Refer a friend": "inviter un ami",
          "Add": "ajouter",
          "Add Wallet": "ajouter un portefeuille",
          "Your current Balance ": "votre solde actuel",
          "Add Amount": "ajouter un montant",
          "Amount": "quantité",
          "History": "l'histoire",
          "Mr. Urban App": "application monsieur urbain",
          "Congratulation !": "Toutes nos félicitations!",
          "DATE": "Date",
          "TIME": "temps",
          "Location": "Emplacement",
          "Please don`t press back until the transaction is complete":
              "Veuillez ne pas appuyer sur retour tant que la transaction n'est pas terminée",
          "No New Notifications": "pas de nouvelles notifications",
          "No Event Shortlisted, Yet !":
              "Aucun événement présélectionné pour le moment !",
          "Available Coupon": "Coupons disponibles",
          "No Coupon": "pas de coupons",
          "Apply": "demander",
          "Resset Password": "Réinitialisation du mot de passe",
          "Please enter your email address to":
              "Veuillez saisir votre adresse e-mail",
          "request a password reset":
              "demander la réinitialisation du mot de passe",
          "New Password": "nouveau mot de passe",
          "confirm Password": "Confirmez le mot de passe",
          "SEND": "envoyer",
          "GoEvent": "aller à l'événement",
          "Sign in": "s'identifier",
          "Mobile number": "numéro de portable",
          "Remember Me": "souviens-toi de moi",
          "Forgot Password?": "mot de passe oublié?",
          "SIGN IN": "s'identifier",
          "Don't have an account?": "Vous n'avez pas de compte ?",
          "Sign up": "S'inscrire",
          "Enter Number": "entrer un nombre",
          "Your password": "votre mot de passe",
          "Referral code": "Code de Parrainage",
          "By continuing, ": "continue,",
          "You agree to GoEvent's \n": "Vous êtes d'accord avec GoEvent\n",
          "Terms of Use ": "conditions d'utilisation",
          "Terms & Conditions": "termes et conditions",
          "Privacy Policy.": "Politique de confidentialité.",
          "SIGN UP": "S'inscrire",
          "Already have an account? ": "Vous avez déjà un compte?",
          "Verification": "vérification",
          "We've send you the verification":
              "Nous vous avons envoyé une vérification",
          "Re-send OTP": "Renvoyer OTP",
          "Comment": "Commenter",
          "Enter comment": "entrer un commentaire",
          "Submit": "présenter ou montrer",
          "Cancel Booking": "Annuler la réservation",
          "Please select the reason for cancellation:":
              "Veuillez sélectionner un motif d'annulation :",
          "Enter reason": "entrer la raison",
          "Confirm": "confirmer",
        },
        'UN_IN': {
          "Settings": "Einstellung",
          "Account Settings": "Account Einstellungen",
          "Profile": "Profil",
          "My Booking": "Meine Buchung",
          "Wallet": "Geldbeutel",
          "Favorite": "Favorit",
          "Notification": "Benachrichtigung",
          "Refer a Friend": "Freund einladen",
          "Dark Mode": "dunkler Modus",
          "Contact Us": "Kontakt",
          "Privacy Policy": "Datenschutz-Bestimmungen",
          "Terms & Condition": "Geschäftsbedingungen",
          "FAQ": "allgemeine Frage",
          "Langauge": "Sprache",
          "Help": "Hilfe",
          "Delete Account": "Konto löschen",
          "Are you sure ?\n You want to delete the account":
              "Sind Sie sicher?\n Sie möchten das Konto löschen",
          "Logout": "Ausloggen",
          "Delete": "löschen",
          "No": "Nein",
          "Are you sure you want to log out?":
              "Möchten Sie sich wirklich abmelden?",
          "Cancel": "Absagen",
          "Yes Logout": "ja abmelden",
          "Search": "Suche",
          "Invite": "einladen",
          "About Event": "über die Veranstaltung",
          "Gallery": "Galerie",
          "Organizer": "Veranstalter",
          "View E-Ticket": "E-Ticket ansehen",
          "Buy More Ticket": "mehr Karten kaufen",
          "Looks like you haven't booked yet":
              "Sieht so aus, als hätten Sie noch nicht gebucht",
          "Members": "Mitglieder",
          "Explore": "suchen",
          "Booking": "Buchung",
          "Tickets": "Fahrkarte",
          "Upcoming": "das bevorstehende",
          "Completed": "Es ist fertig",
          "Cancelled": "Abgebrochen",
          "Download Ticket": "Ticket herunterladen",
          "E-Ticket": "E-Ticket",
          "Event": "Organisation",
          "Date and Hour": "Datum und Stunde",
          "Event Location": "Veranstaltungsort",
          "Event organizer": "Veranstaltungsmanager",
          "Full Name": "Vollständiger Name",
          "Phone": "Telefon",
          "Email": "Email",
          "Seats": "die Sitze",
          "Tax": "tun",
          "Total": "Komplett",
          "Transaction ID": "Transaktions-ID",
          "Payment Methods": "Zahlungsmethode",
          "Status": "Status",
          "Copy": "Kopieren",
          "BUY TICKET": "Ticket kaufen",
          "Trending Events": "trendige Ereignisse",
          "See All": "alles sehen",
          "Upcoming Events": "Kommende Veranstaltungen",
          "Invite your friends": "Lade deine Freunde ein",
          "Get \$20 for ticket": "ERHALTEN SIE 20 \$ FÜR TICKETS",
          "INVITE": "einladen",
          "Nearby You": "nahe bei dir",
          "Event This Month": "Ereignis des Monats",
          "Sponser": "Sponsor",
          "Join": "beitreten",
          "Current Location": "Aktueller Standort",
          "Search...": "Suche...",
          "Angelina Zolly": "Angelina Jolie",
          "2k Followers": "2.000 Follower",
          "Bookmark": "Lesezeichen",
          "Edit Profile": "Profil bearbeiten",
          "Name": "Name",
          "Number": "Anzahl",
          "password": "Passwort",
          "SAVE": "speichern",
          "Event Details": "Informationen zur Veranstaltung",
          "Directions": "Richtlinien",
          "CONTINUE": "fortsetzen",
          "Ticket": "Fahrkarte",
          "Ticket Type": "Art des Tickets",
          "Seat": "Sitz",
          "Coupons": "Gutscheine",
          "Coupon applied !": "Gutschein wurde angewendet!",
          "Apply Coupon": "Gutschein anwenden",
          "Applied Voucher Code": "Angewendeter Gutscheincode",
          "Pay from wallet": "mit Geldbörse bezahlen",
          "GoEvent Balance": "Goevent-Bilanz",
          "Available for Payment ": "zur Zahlung verfügbar",
          "Sub Total:": "Verwenden:",
          "Wallet:": "Geldbeutel:",
          "Coupon Code:": "Gutscheincode:",
          "Tax:": "tun:",
          "Total:": "Komplett:",
          "I Confirm that I am healty": "Ich bestätige, dass ich gesund bin",
          "Select Payment Method": "Wählen Sie die Zahlungsmethode",
          "PAY NOW | ": "Jetzt bezahlen |",
          "Add Your payment information":
              "Fügen Sie Ihre Zahlungsinformationen hinzu",
          "What number is written on card?":
              "Welche Nummer steht auf der Karte?",
          "Number behind the card": "Nummer auf der Rückseite der Karte",
          "CVV": "Lebenslauf",
          "Expiry Date": "Endtermin",
          "MM/YY": "Monat Jahr",
          "Event Venue": "der Veranstaltungsort",
          "Event List Not Found!": "Veranstaltungseintrag nicht gefunden!",
          "Helps & FAQs": "Hilfe und FAQ",
          "Refer a friend": "Freund einladen",
          "Add": "hinzufügen",
          "Add Wallet": "Geldbörse hinzufügen",
          "Your current Balance ": "Ihr aktuelles Guthaben",
          "Add Amount": "Betrag hinzufügen",
          "Amount": "Höhe",
          "History": "Geschichte",
          "Mr. Urban App": "Herr Stadt App",
          "Congratulation !": "Glückwünsche!",
          "DATE": "Datum",
          "TIME": "Zeit",
          "Location": "Ort",
          "Please don`t press back until the transaction is complete":
              "Bitte drücken Sie nicht zurück, bis die Transaktion abgeschlossen ist",
          "No New Notifications": "Keine neuen Benachrichtigungen",
          "No Event Shortlisted, Yet !":
              "Noch keine Veranstaltungen in der engeren Auswahl!",
          "Available Coupon": "Gutscheine verfügbar",
          "No Coupon": "keine Gutscheine",
          "Apply": "anzufordern",
          "Resset Password": "Passwort zurücksetzen",
          "Please enter your email address to":
              "Geben Sie bitte Ihre Email-Adresse ein",
          "request a password reset": "fordere Passwort-Reset an",
          "New Password": "Neues Passwort",
          "confirm Password": "Kennwort bestätigen",
          "SEND": "senden",
          "GoEvent": "goevent",
          "Sign in": "Einloggen",
          "Mobile number": "Handy Nummer",
          "Remember Me": "Erinnere dich an mich",
          "Forgot Password?": "Passwort vergessen?",
          "SIGN IN": "Einloggen",
          "Don't have an account?": "Sie haben kein Konto?",
          "Sign up": "Anmelden",
          "Enter Number": "Nummer eingeben",
          "Your password": "Ihr Passwort",
          "Referral code": "Referenzcode",
          "By continuing, ": "auch weiterhin,",
          "You agree to GoEvent's \n": "Sie stimmen GoEvent\n zu",
          "Terms of Use ": "Nutzungsbedingungen",
          "Terms & Conditions": "Geschäftsbedingungen",
          "Privacy Policy.": "Datenschutz-Bestimmungen.",
          "SIGN UP": "Anmelden",
          "Already have an account? ": "Sie haben bereits ein Konto?",
          "Verification": "Überprüfung",
          "We've send you the verification":
              "Wir haben Ihnen eine Bestätigung gesendet",
          "Re-send OTP": "OTP erneut senden",
          "Comment": "Kommentar",
          "Enter comment": "Kommentar eingeben",
          "Submit": "präsentieren oder zeigen",
          "Cancel Booking": "Buchung stornieren",
          "Please select the reason for cancellation:":
              "Bitte wählen Sie einen Kündigungsgrund aus:",
          "Enter reason": "Grund eingeben",
          "Confirm": "bestätigen",
        },
        'fr_IN': {
          "Settings": "Pengaturan",
          "Account Settings": "pengaturan akun",
          "Profile": "Profil",
          "My Booking": "pemesanan saya",
          "Wallet": "tas kecil",
          "Favorite": "Favorit",
          "Notification": "pemberitahuan",
          "Refer a Friend": "mengundang teman",
          "Dark Mode": "mode gelap",
          "Contact Us": "Kontak",
          "Privacy Policy": "Kebijakan pribadi",
          "Terms & Condition": "syarat dan Ketentuan",
          "FAQ": "pertanyaan Umum",
          "Langauge": "Bahasa",
          "Help": "Tolong",
          "Delete Account": "Hapus akun",
          "Are you sure ?\n You want to delete the account":
              "Anda yakin?\n Anda ingin menghapus akun",
          "Logout": "keluar",
          "Delete": "menghapus",
          "No": "Tidak",
          "Are you sure you want to log out?":
              "Apakah Anda yakin ingin keluar?",
          "Cancel": "Membatalkan",
          "Yes Logout": "ya logout",
          "Search": "Mencari",
          "Invite": "Undang",
          "About Event": "tentang acara tersebut",
          "Gallery": "Galeri",
          "Organizer": "Penyelenggara",
          "View E-Ticket": "lihat e-tiket",
          "Buy More Ticket": "membeli lebih banyak tiket",
          "Looks like you haven't booked yet": "Sepertinya Anda belum memesan",
          "Members": "anggota",
          "Explore": "untuk mencari",
          "Booking": "pemesanan",
          "Tickets": "Tiket",
          "Upcoming": "yang akan datang",
          "Completed": "Selesai",
          "Cancelled": "Dibatalkan",
          "Download Ticket": "unduh tiket",
          "E-Ticket": "tiket elektronik",
          "Event": "Organisasi",
          "Date and Hour": "tanggal dan jam",
          "Event Location": "lokasi acara",
          "Event organizer": "penyelenggara acara",
          "Full Name": "Nama lengkap",
          "Phone": "telepon",
          "Email": "Surel",
          "Seats": "tempat duduk",
          "Tax": "melakukan",
          "Total": "menyelesaikan",
          "Transaction ID": "ID transaksi",
          "Payment Methods": "Cara Pembayaran",
          "Status": "status",
          "Copy": "salinan",
          "BUY TICKET": "beli tiket",
          "Trending Events": "peristiwa yang sedang tren",
          "See All": "Lihat semua",
          "Upcoming Events": "Acara Mendatang",
          "Invite your friends": "Undang temanmu",
          "Get \$20 for ticket": "DAPATKAN \$20 UNTUK TIKET",
          "INVITE": "Undang",
          "Nearby You": "di dekat Anda",
          "Event This Month": "acara bulan ini",
          "Sponser": "sponsor",
          "Join": "Ikuti",
          "Current Location": "Lokasi saat ini",
          "Search...": "Mencari...",
          "Angelina Zolly": "Angelina Jolie",
          "2k Followers": "2k pengikut",
          "Bookmark": "penanda buku",
          "Edit Profile": "Sunting profil",
          "Name": "nama",
          "Number": "Nomor",
          "password": "kata sandi",
          "SAVE": "menyimpan",
          "Event Details": "informasi acara",
          "Directions": "pedoman",
          "CONTINUE": "melanjutkan",
          "Ticket": "Tiket",
          "Ticket Type": "Jenis Tiket",
          "Seat": "kursi",
          "Coupons": "Kupon",
          "Coupon applied !": "Kupon telah diterapkan!",
          "Apply Coupon": "Terapkan Kupon",
          "Applied Voucher Code": "Kode Voucher Terapan",
          "Pay from wallet": "bayar dengan dompet",
          "GoEvent Balance": "saldo goevent",
          "Available for Payment ": "tersedia untuk pembayaran",
          "Sub Total:": "Menggunakan:",
          "Wallet:": "tas kecil:",
          "Coupon Code:": "Kode Kupon:",
          "Tax:": "melakukan:",
          "Total:": "menyelesaikan:",
          "I Confirm that I am healty": "Saya tegaskan bahwa saya sehat",
          "Select Payment Method": "Pilih metode pembayaran",
          "PAY NOW | ": "Bayar Sekarang |",
          "Add Your payment information": "tambahkan informasi pembayaran Anda",
          "What number is written on card?":
              "Nomor berapa yang tertulis di kartu itu?",
          "Number behind the card": "nomor di belakang kartu",
          "CVV": "cvv",
          "Expiry Date": "tanggal akhir",
          "MM/YY": "bulan tahun",
          "Event Venue": "tempat",
          "Event List Not Found!": "Daftar acara tidak ditemukan!",
          "Helps & FAQs": "Bantuan dan FAQ",
          "Refer a friend": "mengundang teman",
          "Add": "menambahkan",
          "Add Wallet": "tambahkan dompet",
          "Your current Balance ": "saldo Anda saat ini",
          "Add Amount": "tambahkan jumlah",
          "Amount": "jumlah",
          "History": "sejarah",
          "Mr. Urban App": "aplikasi mr perkotaan",
          "Congratulation !": "Selamat!",
          "DATE": "tanggal",
          "TIME": "waktu",
          "Location": "Lokasi",
          "Please don`t press back until the transaction is complete":
              "Harap jangan tekan kembali sampai transaksi selesai",
          "No New Notifications": "Tidak ada notifikasi baru",
          "No Event Shortlisted, Yet !": "Belum ada acara yang dipilih!",
          "Available Coupon": "Kupon Tersedia",
          "No Coupon": "tidak ada kupon",
          "Apply": "untuk meminta",
          "Resset Password": "pengaturan ulang kata sandi",
          "Please enter your email address to": "Masukkan alamat email Anda",
          "request a password reset": "permintaan reset kata sandi",
          "New Password": "kata sandi baru",
          "confirm Password": "konfirmasi sandi",
          "SEND": "mengirim",
          "GoEvent": "goevent",
          "Sign in": "masuk",
          "Mobile number": "nomor handphone",
          "Remember Me": "ingat saya",
          "Forgot Password?": "Tidak ingat kata sandi?",
          "SIGN IN": "masuk",
          "Don't have an account?": "Belum punya akun?",
          "Sign up": "Daftar",
          "Enter Number": "masukkan nomor",
          "Your password": "kata sandi Anda",
          "Referral code": "Kode Referensi",
          "By continuing, ": "melanjutkan,",
          "You agree to GoEvent's \n": "Anda setuju dengan GoEvent\n",
          "Terms of Use ": "syarat Penggunaan",
          "Terms & Conditions": "syarat dan Ketentuan",
          "Privacy Policy.": "Kebijakan pribadi.",
          "SIGN UP": "Daftar",
          "Already have an account? ": "Sudah memiliki akun?",
          "Verification": "verifikasi",
          "We've send you the verification":
              "Kami telah mengirimkan verifikasi kepada Anda",
          "Re-send OTP": "Kirim ulang OTP",
          "Comment": "Komentar",
          "Enter comment": "masukkan komentar",
          "Submit": "menyajikan atau menunjukkan",
          "Cancel Booking": "membatalkan pemesanan",
          "Please select the reason for cancellation:":
              "Harap pilih alasan pembatalan:",
          "Enter reason": "masukkan alasan",
          "Confirm": "Konfirmasi",
        },
        'pt_IN': {
          "Settings": "Ajustamento",
          "Account Settings": "Configurações da conta",
          "Profile": "Perfil",
          "My Booking": "Minha reserva",
          "Wallet": "bolsa",
          "Favorite": "Favorito",
          "Notification": "notificação",
          "Refer a Friend": "convidar amigo",
          "Dark Mode": "modo escuro",
          "Contact Us": "Contato",
          "Privacy Policy": "Política de Privacidade",
          "Terms & Condition": "termos e Condições",
          "FAQ": "pergunta geral",
          "Langauge": "Linguagem",
          "Help": "ajuda",
          "Delete Account": "deletar conta",
          "Are you sure ?\n You want to delete the account":
              "Tem certeza?\n Deseja excluir a conta",
          "Logout": "sair",
          "Delete": "excluir",
          "No": "Não",
          "Are you sure you want to log out?": "Tem certeza que deseja sair?",
          "Cancel": "Cancelar",
          "Yes Logout": "sim sair",
          "Search": "Procurar",
          "Invite": "convidar",
          "About Event": "sobre o evento",
          "Gallery": "Galeria",
          "Organizer": "Organizador",
          "View E-Ticket": "ver e-ticket",
          "Buy More Ticket": "comprar mais ingressos",
          "Looks like you haven't booked yet":
              "Parece que você ainda não reservou",
          "Members": "membros",
          "Explore": "procurar",
          "Booking": "reserva",
          "Tickets": "Bilhete",
          "Upcoming": "o próximo",
          "Completed": "Está pronto",
          "Cancelled": "Cancelado",
          "Download Ticket": "baixar bilhete",
          "E-Ticket": "bilhete eletrônico",
          "Event": "Organização",
          "Date and Hour": "data e hora",
          "Event Location": "Local do evento",
          "Event organizer": "organizador de evento",
          "Full Name": "Nome completo",
          "Phone": "telefone",
          "Email": "O email",
          "Seats": "os assentos",
          "Tax": "Faz",
          "Total": "completo",
          "Transaction ID": "ID da transação",
          "Payment Methods": "Forma de pagamento",
          "Status": "status",
          "Copy": "cópia de",
          "BUY TICKET": "comprar bilhete",
          "Trending Events": "eventos de tendências",
          "See All": "ver tudo",
          "Upcoming Events": "próximos eventos",
          "Invite your friends": "convide seus amigos",
          "Get \$20 for ticket": "GANHE \$ 20 PARA INGRESSOS",
          "INVITE": "convidar",
          "Nearby You": "perto de você",
          "Event This Month": "evento do mês",
          "Sponser": "patrocinador",
          "Join": "Junte-se",
          "Current Location": "Localização atual",
          "Search...": "Procurar...",
          "Angelina Zolly": "Angelina Jolie",
          "2k Followers": "2k seguidores",
          "Bookmark": "marca páginas",
          "Edit Profile": "editar Perfil",
          "Name": "nome",
          "Number": "Número",
          "password": "senha",
          "SAVE": "Salve ",
          "Event Details": "informações do evento",
          "Directions": "diretrizes",
          "CONTINUE": "Prosseguir",
          "Ticket": "Bilhete",
          "Ticket Type": "Tipo de bilhete",
          "Seat": "assento",
          "Coupons": "cupons",
          "Coupon applied !": "O cupom foi aplicado!",
          "Apply Coupon": "Aplicar cupom",
          "Applied Voucher Code": "Código de Voucher Aplicado",
          "Pay from wallet": "pagar com carteira",
          "GoEvent Balance": "saldo do evento",
          "Available for Payment ": "disponível para pagamento",
          "Sub Total:": "Usar:",
          "Wallet:": "bolsa:",
          "Coupon Code:": "Código do cupom:",
          "Tax:": "Faz:",
          "Total:": "completo:",
          "I Confirm that I am healty": "Eu confirmo que sou saudável",
          "Select Payment Method": "Selecione o método de pagamento",
          "PAY NOW | ": "Pague Agora |",
          "Add Your payment information":
              "adicione suas informações de pagamento",
          "What number is written on card?":
              "Que número está escrito no cartão?",
          "Number behind the card": "número no verso do cartão",
          "CVV": "cvv",
          "Expiry Date": "data final",
          "MM/YY": "mês ano",
          "Event Venue": "o local",
          "Event List Not Found!": "Lista de eventos não encontrada!",
          "Helps & FAQs": "Ajuda e perguntas frequentes",
          "Refer a friend": "convidar amigo",
          "Add": "adicionar",
          "Add Wallet": "adicionar carteira",
          "Your current Balance ": "seu saldo atual",
          "Add Amount": "adicionar quantidade",
          "Amount": "montante",
          "History": "história",
          "Mr. Urban App": "sr. aplicativo urbano",
          "Congratulation !": "Parabéns!",
          "DATE": "encontro",
          "TIME": "Tempo",
          "Location": "Localização",
          "Please don`t press back until the transaction is complete":
              "Por favor, não pressione de volta até que a transação seja concluída",
          "No New Notifications": "Nenhuma nova notificação",
          "No Event Shortlisted, Yet !":
              "Ainda não há eventos pré-selecionados!",
          "Available Coupon": "Cupons Disponíveis",
          "No Coupon": "sem cupons",
          "Apply": "para solicitar",
          "Resset Password": "Redefinição de senha",
          "Please enter your email address to":
              "Por favor, indique o seu endereço de e-mail",
          "request a password reset": "solicitar redefinição de senha",
          "New Password": "Nova Senha",
          "confirm Password": "Confirme a Senha",
          "SEND": "mandar",
          "GoEvent": "ir evento",
          "Sign in": "entrar",
          "Mobile number": "número de celular",
          "Remember Me": "lembre de mim",
          "Forgot Password?": "Esqueceu a senha?",
          "SIGN IN": "entrar",
          "Don't have an account?": "Não tem uma conta?",
          "Sign up": "Inscrever-se",
          "Enter Number": "insira numeros",
          "Your password": "sua senha",
          "Referral code": "Código de Referencia",
          "By continuing, ": "continuando,",
          "You agree to GoEvent's \n": "Você concorda com GoEvent\n",
          "Terms of Use ": "termos de uso",
          "Terms & Conditions": "termos e Condições",
          "Privacy Policy.": "Política de Privacidade.",
          "SIGN UP": "Inscrever-se",
          "Already have an account? ": "já tem uma conta?",
          "Verification": "verificação",
          "We've send you the verification": "Enviamos a você a verificação",
          "Re-send OTP": "Reenviar OTP",
          "Comment": "Comente",
          "Enter comment": "digite comentário",
          "Submit": "apresentar ou mostrar",
          "Cancel Booking": "cancelar reserva",
          "Please select the reason for cancellation:":
              "Por favor, selecione um motivo para cancelamento:",
          "Enter reason": "digite o motivo",
          "Confirm": "confirme",
        },
        'es_IN': {
          "Settings": "Ajustamiento",
          "Account Settings": "Configuraciones de la cuenta",
          "Profile": "Perfil",
          "My Booking": "mi reserva",
          "Wallet": "cartera",
          "Favorite": "Favorito",
          "Notification": "notificación",
          "Refer a Friend": "invitar a un amigo",
          "Dark Mode": "modo oscuro",
          "Contact Us": "Contacto",
          "Privacy Policy": "Política de privacidad",
          "Terms & Condition": "Términos y condiciones",
          "FAQ": "pregunta general",
          "Langauge": "Idioma",
          "Help": "ayudar",
          "Delete Account": "borrar cuenta",
          "Are you sure ?\n You want to delete the account":
              "¿Estás seguro?\n Quieres eliminar la cuenta",
          "Logout": "cerrar sesión",
          "Delete": "Eliminar",
          "No": "No",
          "Are you sure you want to log out?":
              "¿Está seguro de que desea cerrar la sesión?",
          "Cancel": "Cancelar",
          "Yes Logout": "sí cerrar sesión",
          "Search": "Buscar",
          "Invite": "invitar",
          "About Event": "sobre el evento",
          "Gallery": "Galería",
          "Organizer": "Organizador",
          "View E-Ticket": "ver billete electrónico",
          "Buy More Ticket": "comprar más boletos",
          "Looks like you haven't booked yet":
              "Parece que aún no has reservado",
          "Members": "miembros",
          "Explore": "buscar",
          "Booking": "reserva",
          "Tickets": "Boleto",
          "Upcoming": "el proximo",
          "Completed": "Está terminado",
          "Cancelled": "Cancelado",
          "Download Ticket": "descargar boleto",
          "E-Ticket": "billete electrónico",
          "Event": "Organización",
          "Date and Hour": "fecha y hora",
          "Event Location": "ubicación del evento",
          "Event organizer": "organizador de eventos",
          "Full Name": "Nombre completo",
          "Phone": "teléfono",
          "Email": "Correo electrónico",
          "Seats": "los asientos",
          "Tax": "hacer",
          "Total": "completo",
          "Transaction ID": "ID de transacción",
          "Payment Methods": "método de pago",
          "Status": "estado",
          "Copy": "Copiar",
          "BUY TICKET": "comprar boleto",
          "Trending Events": "eventos de tendencia",
          "See All": "ver todo",
          "Upcoming Events": "Próximos Eventos",
          "Invite your friends": "invita a tus amigos",
          "Get \$20 for ticket": "OBTÉN \$20 POR ENTRADAS",
          "INVITE": "invitar",
          "Nearby You": "cerca de usted",
          "Event This Month": "evento del mes",
          "Sponser": "patrocinador",
          "Join": "entrar",
          "Current Location": "Ubicación actual",
          "Search...": "Buscar...",
          "Angelina Zolly": "Angelina Jolie",
          "2k Followers": "2k seguidores",
          "Bookmark": "marcador",
          "Edit Profile": "Editar perfil",
          "Name": "nombre",
          "Number": "Número",
          "password": "contraseña",
          "SAVE": "salvar",
          "Event Details": "Información del Evento",
          "Directions": "pautas",
          "CONTINUE": "Seguir",
          "Ticket": "Boleto",
          "Ticket Type": "Tipo de billete",
          "Seat": "asiento",
          "Coupons": "cupones",
          "Coupon applied !": "¡El cupón ha sido aplicado!",
          "Apply Coupon": "Aplicar cupón",
          "Applied Voucher Code": "Código de cupón aplicado",
          "Pay from wallet": "pagar con billetera",
          "GoEvent Balance": "saldo del evento",
          "Available for Payment ": "disponible para pago",
          "Sub Total:": "Utilizar:",
          "Wallet:": "cartera:",
          "Coupon Code:": "Código promocional:",
          "Tax:": "hacer:",
          "Total:": "completo:",
          "I Confirm that I am healty": "Confirmo que estoy sano",
          "Select Payment Method": "Seleccionar método de pago",
          "PAY NOW | ": "Pague ahora |",
          "Add Your payment information": "agrega tu información de pago",
          "What number is written on card?":
              "¿Qué número está escrito en la tarjeta?",
          "Number behind the card": "número en el reverso de la tarjeta",
          "CVV": "CVV",
          "Expiry Date": "fecha final",
          "MM/YY": "mes año",
          "Event Venue": "el lugar",
          "Event List Not Found!": "¡Lista de eventos no encontrada!",
          "Helps & FAQs": "Ayuda y preguntas frecuentes",
          "Refer a friend": "invitar a un amigo",
          "Add": "agregar",
          "Add Wallet": "agregar billetera",
          "Your current Balance ": "su saldo actual",
          "Add Amount": "añadir cantidad",
          "Amount": "Monto",
          "History": "historia",
          "Mr. Urban App": "mr aplicación urbana",
          "Congratulation !": "¡Felicidades!",
          "DATE": "fecha",
          "TIME": "hora",
          "Location": "Localización",
          "Please don`t press back until the transaction is complete":
              "Por favor, no presione hacia atrás hasta que se complete la transacción.",
          "No New Notifications": "no hay notificaciones nuevas",
          "No Event Shortlisted, Yet !":
              "¡Aún no hay eventos preseleccionados!",
          "Available Coupon": "Cupones disponibles",
          "No Coupon": "sin cupones",
          "Apply": "solicitar",
          "Resset Password": "restablecimiento de contraseña",
          "Please enter your email address to":
              "Por favor, introduzca su dirección de correo electrónico",
          "request a password reset":
              "petición para la recuperación de contraseña",
          "New Password": "Nueva contraseña",
          "confirm Password": "Confirmar contraseña",
          "SEND": "enviar",
          "GoEvent": "goevent",
          "Sign in": "registrarse",
          "Mobile number": "número de teléfono móvil",
          "Remember Me": "Recuérdame",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "SIGN IN": "registrarse",
          "Don't have an account?": "¿No tienes una cuenta?",
          "Sign up": "Regístrate",
          "Enter Number": "ingresar número",
          "Your password": "tu contraseña",
          "Referral code": "código de referencia",
          "By continuing, ": "continuo,",
          "You agree to GoEvent's \n": "Estás de acuerdo con GoEvent\n",
          "Terms of Use ": "condiciones de uso",
          "Terms & Conditions": "Términos y condiciones",
          "Privacy Policy.": "Política de privacidad.",
          "SIGN UP": "Regístrate",
          "Already have an account? ": "¿Ya tienes una cuenta?",
          "Verification": "verificación",
          "We've send you the verification": "Te hemos enviado verificación",
          "Re-send OTP": "Reenviar OTP",
          "Comment": "Comentario",
          "Enter comment": "ingresar comentario",
          "Submit": "presentar o mostrar",
          "Cancel Booking": "cancelar reserva",
          "Please select the reason for cancellation:":
              "Seleccione un motivo de cancelación:",
          "Enter reason": "ingrese el motivo",
          "Confirm": "confirmar",
        },
        'tr_IN': {
          "Settings": "ayar",
          "Account Settings": "hesap ayarları",
          "Profile": "Profil",
          "My Booking": "rezervasyonum",
          "Wallet": "el çantası",
          "Favorite": "Favori",
          "Notification": "bildirim",
          "Refer a Friend": "arkadaş davet etmek",
          "Dark Mode": "karanlık mod",
          "Contact Us": "Temas",
          "Privacy Policy": "Gizlilik Politikası",
          "Terms & Condition": "Şartlar ve koşullar",
          "FAQ": "Genel Soru",
          "Langauge": "Dil",
          "Help": "Yardım Edin",
          "Delete Account": "Hesabı sil",
          "Are you sure ?\n You want to delete the account":
              "Emin misiniz?\n Hesabı silmek istiyorsunuz",
          "Logout": "çıkış Yap",
          "Delete": "silmek",
          "No": "hayır",
          "Are you sure you want to log out?":
              "Oturumu kapatmak istediğinizden emin misiniz?",
          "Cancel": "İptal",
          "Yes Logout": "evet oturumu kapat",
          "Search": "Arama",
          "Invite": "Davet et",
          "About Event": "olay hakkında",
          "Gallery": "Galeri",
          "Organizer": "Organizatör",
          "View E-Ticket": "e-bileti görüntüle",
          "Buy More Ticket": "daha fazla bilet al",
          "Looks like you haven't booked yet":
              "Görünüşe göre henüz rezervasyon yapmamışsın",
          "Members": "üyeler",
          "Explore": "aramak",
          "Booking": "rezervasyon",
          "Tickets": "Bilet",
          "Upcoming": "yaklaşan",
          "Completed": "Bitti",
          "Cancelled": "İptal edildi",
          "Download Ticket": "bilet indir",
          "E-Ticket": "elektronik bilet",
          "Event": "organizasyon",
          "Date and Hour": "tarih ve saat",
          "Event Location": "olay yeri",
          "Event organizer": "etkinlik düzenleyici",
          "Full Name": "Ad Soyad",
          "Phone": "telefon",
          "Email": "e-posta",
          "Seats": "koltuklar",
          "Tax": "yapmak",
          "Total": "tamamlamak",
          "Transaction ID": "İşlem Kimliği",
          "Payment Methods": "Ödeme şekli",
          "Status": "durum",
          "Copy": "kopyalamak",
          "BUY TICKET": "bilet al",
          "Trending Events": "trend olaylar",
          "See All": "tümünü Gör",
          "Upcoming Events": "Yaklaşan Etkinlikler",
          "Invite your friends": "arkadaşlarını davet et",
          "Get \$20 for ticket": "BİLETLER İÇİN 20 \$ ALIN",
          "INVITE": "Davet et",
          "Nearby You": "sana yakın",
          "Event This Month": "ayın olayı",
          "Sponser": "sponsor",
          "Join": "katılmak",
          "Current Location": "Mevcut konum",
          "Search...": "Arama...",
          "Angelina Zolly": "Angelina Jolie",
          "2k Followers": "2k takipçi",
          "Bookmark": "yer imi",
          "Edit Profile": "profili Düzenle",
          "Name": "isim",
          "Number": "Sayı",
          "password": "parola",
          "SAVE": "kayıt etmek",
          "Event Details": "Etkinlik bilgisi",
          "Directions": "yönergeler",
          "CONTINUE": "devam et",
          "Ticket": "Bilet",
          "Ticket Type": "bilet tipi",
          "Seat": "koltuk",
          "Coupons": "Kuponlar",
          "Coupon applied !": "Kupon uygulandı!",
          "Apply Coupon": "kuponu onayla",
          "Applied Voucher Code": "Geçerli Kupon Kodu",
          "Pay from wallet": "cüzdanla öde",
          "GoEvent Balance": "denge dengesi",
          "Available for Payment ": "ödeme için uygun",
          "Sub Total:": "Kullanmak:",
          "Wallet:": "el çantası:",
          "Coupon Code:": "Kupon Kodu:",
          "Tax:": "yapmak:",
          "Total:": "tamamlamak:",
          "I Confirm that I am healty": "sağlıklı olduğumu onaylıyorum",
          "Select Payment Method": "ödeme türünü seçin",
          "PAY NOW | ": "Şimdi Öde |",
          "Add Your payment information": "ödeme bilgilerinizi ekleyin",
          "What number is written on card?": "Kartta hangi numara yazıyor?",
          "Number behind the card": "kartın arkasındaki numara",
          "CVV": "özgeçmiş",
          "Expiry Date": "bitiş tarihi",
          "MM/YY": "ay yıl",
          "Event Venue": "Mekan",
          "Event List Not Found!": "Etkinlik listesi bulunamadı!",
          "Helps & FAQs": "Yardım ve SSS",
          "Refer a friend": "arkadaş davet etmek",
          "Add": "Ekle",
          "Add Wallet": "cüzdan ekle",
          "Your current Balance ": "mevcut bakiyeniz",
          "Add Amount": "miktar ekle",
          "Amount": "miktar",
          "History": "Tarih",
          "Mr. Urban App": "bay kentsel uygulama",
          "Congratulation !": "Tebrikler!",
          "DATE": "tarih",
          "TIME": "zaman",
          "Location": "Konum",
          "Please don`t press back until the transaction is complete":
              "Lütfen işlem tamamlanana kadar geri basmayın",
          "No New Notifications": "yeni bildirim yok",
          "No Event Shortlisted, Yet !":
              "Henüz kısa listeye alınmış etkinlik yok!",
          "Available Coupon": "Kuponlar Mevcut",
          "No Coupon": "kupon yok",
          "Apply": "talep etmek",
          "Resset Password": "parola sıfırlama",
          "Please enter your email address to":
              "lütfen e-mail adresinizi giriniz",
          "request a password reset": "şifre sıfırlama isteği",
          "New Password": "Yeni Şifre",
          "confirm Password": "Şifreyi Onayla",
          "SEND": "göndermek",
          "GoEvent": "olay",
          "Sign in": "kayıt olmak",
          "Mobile number": "cep numarası",
          "Remember Me": "beni Hatırla",
          "Forgot Password?": "Parolanızı mı unuttunuz?",
          "SIGN IN": "kayıt olmak",
          "Don't have an account?": "Hesabınız yok mu?",
          "Sign up": "Üye olmak",
          "Enter Number": "numarayı girin",
          "Your password": "şifreniz",
          "Referral code": "Yönlendirme Kodu",
          "By continuing, ": "devam ediyor,",
          "You agree to GoEvent's \n": "GoEvent'e katılıyorsunuz\n",
          "Terms of Use ": "kullanım Şartları",
          "Terms & Conditions": "Şartlar ve koşullar",
          "Privacy Policy.": "Gizlilik Politikası.",
          "SIGN UP": "Üye olmak",
          "Already have an account? ": "Zaten hesabınız var mı?",
          "Verification": "doğrulama",
          "We've send you the verification": "Size doğrulama gönderdik",
          "Re-send OTP": "OTP'yi yeniden gönder",
          "Comment": "Yorum Yap",
          "Enter comment": "yorum girin",
          "Submit": "sunmak veya göstermek",
          "Cancel Booking": "rezervasyon iptali",
          "Please select the reason for cancellation:":
              "Lütfen bir iptal nedeni seçin:",
          "Enter reason": "sebep girin",
          "Confirm": "teyit etmek",
        },
        'vi_IN': {
          "Settings": "điều chỉnh",
          "Account Settings": "cài đặt tài khoản",
          "Profile": "Hồ sơ",
          "My Booking": "đặt phòng của tôi",
          "Wallet": "cái ví",
          "Favorite": "Yêu thích",
          "Notification": "thông báo",
          "Refer a Friend": "mời bạn bè",
          "Dark Mode": "chế độ tối",
          "Contact Us": "Tiếp xúc",
          "Privacy Policy": "Chính sách bảo mật",
          "Terms & Condition": "các điều khoản và điều kiện",
          "FAQ": "câu hỏi chung",
          "Langauge": "Ngôn ngữ",
          "Help": "Cứu giúp",
          "Delete Account": "xóa tài khoản",
          "Are you sure ?\n You want to delete the account":
              "Bạn có chắc không?\n Bạn muốn xóa tài khoản",
          "Logout": "đăng xuất",
          "Delete": "xóa bỏ",
          "No": "Không",
          "Are you sure you want to log out?":
              "Bạn có chắc chắn bạn muốn thoát?",
          "Cancel": "Hủy bỏ",
          "Yes Logout": "vâng đăng xuất",
          "Search": "Tìm kiếm",
          "Invite": "mời",
          "About Event": "về sự kiện",
          "Gallery": "Bộ sưu tập",
          "Organizer": "người tổ chức",
          "View E-Ticket": "xem vé điện tử",
          "Buy More Ticket": "mua thêm vé",
          "Looks like you haven't booked yet": "Có vẻ như bạn chưa đặt trước",
          "Members": "các thành viên",
          "Explore": "tìm kiếm",
          "Booking": "Đặt trước",
          "Tickets": "Vé",
          "Upcoming": "sắp tới",
          "Completed": "Nó đã hoàn thành",
          "Cancelled": "Đã hủy",
          "Download Ticket": "tải về vé",
          "E-Ticket": "vé điện tử",
          "Event": "Tổ chức",
          "Date and Hour": "ngày và giờ",
          "Event Location": "vị trí sự kiện",
          "Event organizer": "người tổ chức sự kiện",
          "Full Name": "Họ và tên",
          "Phone": "điện thoại",
          "Email": "E-mail",
          "Seats": "ghế ngồi",
          "Tax": "làm",
          "Total": "hoàn thành",
          "Transaction ID": "ID giao dịch",
          "Payment Methods": "phương thức thanh toán",
          "Status": "tình trạng",
          "Copy": "sao chép",
          "BUY TICKET": "mua vé",
          "Trending Events": "sự kiện thịnh hành",
          "See All": "nhìn thấy tất cả",
          "Upcoming Events": "sự kiện sắp tới",
          "Invite your friends": "mời bạn bè của bạn",
          "Get \$20 for ticket": "NHẬN \$20 CHO VÉ",
          "INVITE": "mời",
          "Nearby You": "gần bạn",
          "Event This Month": "sự kiện của tháng",
          "Sponser": "nhà tài trợ",
          "Join": "tham gia",
          "Current Location": "Vị trí hiện tại",
          "Search...": "Tìm kiếm...",
          "Angelina Zolly": "Angelina Jolie",
          "2k Followers": "2k người theo dõi",
          "Bookmark": "đánh dấu trang",
          "Edit Profile": "chỉnh sửa hồ sơ",
          "Name": "Tên",
          "Number": "Số",
          "password": "mật khẩu mở khóa",
          "SAVE": "tiết kiệm",
          "Event Details": "thông tin sự kiện",
          "Directions": "hướng dẫn",
          "CONTINUE": "tiếp tục",
          "Ticket": "Vé",
          "Ticket Type": "loại vé",
          "Seat": "ghế ngồi",
          "Coupons": "phiếu giảm giá",
          "Coupon applied !": "Phiếu giảm giá đã được áp dụng!",
          "Apply Coupon": "áp dụng phiếu giảm giá",
          "Applied Voucher Code": "Mã Voucher áp dụng",
          "Pay from wallet": "thanh toán bằng ví",
          "GoEvent Balance": "số dư goevent",
          "Available for Payment ": "có sẵn để thanh toán",
          "Sub Total:": "Sử dụng:",
          "Wallet:": "cái ví:",
          "Coupon Code:": "Mã giảm giá:",
          "Tax:": "làm:",
          "Total:": "hoàn thành:",
          "I Confirm that I am healty": "Tôi xác nhận rằng tôi khỏe mạnh",
          "Select Payment Method": "Chọn phương thức thanh toán",
          "PAY NOW | ": "Thanh toán ngay |",
          "Add Your payment information": "thêm thông tin thanh toán của bạn",
          "What number is written on card?": "Số nào được viết trên thẻ?",
          "Number behind the card": "số ở mặt sau của thẻ",
          "CVV": "cvv",
          "Expiry Date": "ngày cuối",
          "MM/YY": "năm tháng",
          "Event Venue": "địa điểm",
          "Event List Not Found!": "Không tìm thấy danh sách sự kiện!",
          "Helps & FAQs": "Trợ giúp và Câu hỏi thường gặp",
          "Refer a friend": "mời bạn bè",
          "Add": "cộng",
          "Add Wallet": "thêm ví",
          "Your current Balance ": "Số dư hiện tại của bạn",
          "Add Amount": "thêm số tiền",
          "Amount": "số lượng",
          "History": "lịch sử",
          "Mr. Urban App": "ứng dụng ông đô thị",
          "Congratulation !": "Chúc mừng!",
          "DATE": "ngày",
          "TIME": "thời gian",
          "Location": "Vị trí",
          "Please don`t press back until the transaction is complete":
              "Vui lòng không nhấn lại cho đến khi giao dịch hoàn tất",
          "No New Notifications": "không có thông báo mới",
          "No Event Shortlisted, Yet !":
              "Chưa có sự kiện nào lọt vào danh sách rút gọn!",
          "Available Coupon": "phiếu giảm giá có sẵn",
          "No Coupon": "không có phiếu giảm giá",
          "Apply": "yêu cầu",
          "Resset Password": "đặt lại mật khẩu",
          "Please enter your email address to":
              "Hãy điền địa chỉ email của bạn",
          "request a password reset": "yêu cầu đặt lại mật khẩu",
          "New Password": "mật khẩu mới",
          "confirm Password": "Xác nhận mật khẩu",
          "SEND": "gửi",
          "GoEvent": "tổ chức sự kiện",
          "Sign in": "đăng nhập",
          "Mobile number": "Số điện thoại",
          "Remember Me": "nhớ tôi",
          "Forgot Password?": "Quên mật khẩu?",
          "SIGN IN": "đăng nhập",
          "Don't have an account?": "Không có một tài khoản?",
          "Sign up": "Đăng ký",
          "Enter Number": "nhập số",
          "Your password": "mật khẩu của bạn",
          "Referral code": "Mã giới thiệu",
          "By continuing, ": "tiếp tục,",
          "You agree to GoEvent's \n": "Bạn đồng ý với GoEvent\n",
          "Terms of Use ": "điều khoản sử dụng",
          "Terms & Conditions": "các điều khoản và điều kiện",
          "Privacy Policy.": "Chính sách bảo mật.",
          "SIGN UP": "Đăng ký",
          "Already have an account? ":
              "Bạn co săn san để tạo một tai khoản?",
          "Verification": "xác minh",
          "We've send you the verification":
              "Chúng tôi đã gửi cho bạn xác minh",
          "Re-send OTP": "Gửi lại OTP",
          "Comment": "Nhận xét",
          "Enter comment": "nhập bình luận",
          "Submit": "để trình bày hoặc để hiển thị",
          "Cancel Booking": "hủy đặt phòng",
          "Please select the reason for cancellation:":
              "Vui lòng chọn lý do hủy:",
          "Enter reason": "nhập lý do",
          "Confirm": "xác nhận",
        }
        // 'ar_IN': {}
      };
}
